### ISSUE TITLE
Configure name of the file data

### ISSUE THREAD

**Issue by probert94** [amura11/ha-rest-file-command#12]
### Checklist

- [x] I have filled out the template to the best of my ability.
- [x] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [x] This issue is not a duplicate feature request of [previous feature requests](https://github.com/amura11/ha-secret-service/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I would like to upload images from my Doorbell to "Immich" (selfhosted alternative to Google Photos).
The API wants the image to be uploaded as `assetData` while this integration seems to always use the key `file`.
Also I would need to add additional data to the request, like `fileCreatedAt` etc. and I am not sure if that is possible.

### Describe the solution you'd like

I would like to be able to define the formdata key of the file and add additional, "normal" payload fields.

### Describe alternatives you've considered

The only alternative I see right now is to use "shell_command" integration with curl.

### Additional context

An example request with curl, regarding the [official API documentation](https://immich.app/docs/api/upload-asset):
```
curl -L '/api/assets' \
-H 'Content-Type: multipart/form-data' \
-H 'Accept: application/json' \
-F 'assetData=@"/path/to/file"' \
-F 'fileCreatedAt="2025-03-17T09:03:18.000Z"' \
-F 'fileModifiedAt="2025-03-17T09:03:18.000Z"'
```

**Comment by amura11** [comment]
So sorry for taking months to answer! I don't get my GH very often.

That should be pretty doable, add a configuration value for the filename and for a dictionary of additional data. I'll take a look at adding this over the next week or so

**Comment by amura11** [comment]
Should be fixed in https://github.com/amura11/ha-rest-file-command/pull/22

You can now define you service as:
```
rest_file_command:
    immich_upload:
        url: "https://immich.tld"
        method: put
        filename: "upload_{{ now().strftime('%Y%m%d') }}.jpg"
        form_field_name: "assetData"
        form_data:
          fileCreatedAt: "{{ now().isoformat() }}"
          fileModifiedAt: "{{ now().isoformat() }}"
```

Let me know if you run into any issues :)
